name: bananoTrack Project Automation (New Projects)

on:
  issues:
    types: [opened, assigned, closed, reopened]
  pull_request:
    types: [opened, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'assigned'
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          # Cambia este URL por el de tu proyecto real
          project-url: https://github.com/users/CarlosMaroRuiz/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

  move_assigned_to_progress:
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: Move to In Progress
        run: |
          echo "Issue assigned - would move to In Progress"
          echo "Issue number: ${{ github.event.issue.number }}"
          # Para implementar el movimiento necesitas obtener los IDs específicos
          # del proyecto usando GitHub CLI o GraphQL API

  close_item:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Close item
        run: |
          echo "Item closed - would move to Done"
          echo "Item number: ${{ github.event.issue.number || github.event.pull_request.number }}"