name: bananoTrack Project Automation (Complete)

on:
  issues:
    types: [opened, assigned, closed, reopened]
  pull_request:
    types: [opened, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          # Tu proyecto correcto
          project-url: https://github.com/users/CarlosMaroRuiz/projects/1
          github-token: ${{ secrets.PAT_TOKEN }}

  move_to_in_progress:
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: Get project data
        id: get_project_data
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              query($owner: String!, $repo: String!, $issueNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issueNumber) {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          id
                          title
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const variables = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issueNumber: context.issue.number
            };
            
            const result = await github.graphql(query, variables);
            console.log('Project items:', JSON.stringify(result, null, 2));
            return result;

  move_to_done:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Move to Done
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Item closed, should move to Done');
            console.log('Issue/PR number:', context.issue?.number || context.payload.pull_request?.number);